# Generated by Django 2.2.7 on 2020-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='city_name_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='country_name_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['name'], name='province_name_idx'),
        ),
    ]
