# Generated by Django 2.2.7 on 2020-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191127_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
