# Generated by Django 2.2.7 on 2020-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='mod_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'published', 'text'], name='post_idx'),
        ),
    ]
