# Generated by Django 2.2.7 on 2020-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['user', 'time_start', 'time_finish', 'duration', 'track_length'], name='track_idx'),
        ),
    ]
